version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "14250:14250"
      - "16686:16686"
  backend:
    build:
      context: ./packages/backend
    ports:
      - 3000:3000
    volumes:
      - ./packages/backend:/app
    depends_on:
      - jaeger